import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user || user.role !== 'admin') {
      return Response.json({ error: 'Admin access required' }, { status: 403 });
    }

    const bandsData = [
      { name: 'Progressive Band', parish: 'Saint Patrick', village_community: 'Grandbay', category: 'Band', era: '1930s', era_from: 1930, era_to: 1939, genre: 'Pre-War Jazz / Roots', status: 'dissolved' },
      { name: 'Baby Jazz Band', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1930s', era_from: 1930, era_to: 1939, genre: 'Jazz', status: 'dissolved' },
      { name: 'Blazing Boys', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1940s–1950s', era_from: 1940, era_to: 1950, genre: 'Jazz / Mambo / Swing', status: 'dissolved' },
      { name: 'Boston Hot Shots', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1940s–1950s', era_from: 1940, era_to: 1950, genre: 'Jazz / Mambo / Swing', status: 'dissolved' },
      { name: 'C G Phillip Jazz  Band', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1940s–1950s', era_from: 1940, era_to: 1950, genre: 'Jazz', status: 'dissolved' },
      { name: 'Casimir Bros', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1940s–1950s', era_from: 1940, era_to: 1950, genre: 'Jazz / Mambo / Swing', status: 'dissolved' },
      { name: 'GJ Orchestra', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1940s–1950s', era_from: 1940, era_to: 1950, genre: 'Jazz / Mambo / Swing', status: 'dissolved' },
      { name: 'Peters Band', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1940s–1950s', era_from: 1940, era_to: 1950, genre: 'Jazz / Mambo / Swing', status: 'dissolved' },
      { name: 'Scullo Mambo', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1940s–1950s', era_from: 1940, era_to: 1950, genre: 'Jazz / Mambo / Swing', status: 'dissolved' },
      { name: 'Echoes', parish: 'Saint Joseph', village_community: 'St. Joseph', category: 'Band', era: '1940s–1950s', era_from: 1940, era_to: 1950, genre: 'Jazz / Mambo / Swing', status: 'dissolved' },
      { name: 'Elijah (Licja Steel Band)', parish: 'Saint Peter', village_community: 'Colihaut', category: 'Steel Band', era: '1950s–2000s', era_from: 1950, era_to: 2000, genre: 'Steel Band', status: 'unknown' },
      { name: 'Londonderry  Steel Harmonites', parish: 'Saint Andrew', village_community: 'Londonderry - Wesley', category: 'Steel Band', era: '1950s–2000s', era_from: 1950, era_to: 2000, genre: 'Steel Band', status: 'unknown' },
      { name: 'Sout Stars', parish: 'Saint Luke', village_community: 'Pt.Michel', category: 'Steel Band', era: '1950s–2000s', era_from: 1950, era_to: 2000, genre: 'Steel Band', status: 'unknown' },
      { name: 'Asto Cats', parish: 'Saint George', village_community: 'Roseau', category: 'Steel Band', era: '1950s–2000s', era_from: 1950, era_to: 2000, genre: 'Steel Band', status: 'unknown' },
      { name: 'Chocolate County', parish: 'Saint George', village_community: 'Roseau', category: 'Steel Band', era: '1950s–2000s', era_from: 1950, era_to: 2000, genre: 'Steel Band', status: 'unknown' },
      { name: 'D-Special', parish: 'Saint George', village_community: 'Roseau', category: 'Steel Band', era: '1950s–2000s', era_from: 1950, era_to: 2000, genre: 'Steel Band', status: 'unknown' },
      { name: 'Esso', parish: 'Saint George', village_community: 'Roseau', category: 'Steel Band', era: '1950s–2000s', era_from: 1950, era_to: 2000, genre: 'Steel Band', status: 'unknown' },
      { name: 'Fanta Pan', parish: 'Saint George', village_community: 'Roseau', category: 'Steel Band', era: '1950s–2000s', era_from: 1950, era_to: 2000, genre: 'Steel Band', status: 'unknown' },
      { name: 'Limacol', parish: 'Saint George', village_community: 'Roseau', category: 'Steel Band', era: '1950s–2000s', era_from: 1950, era_to: 2000, genre: 'Steel Band', status: 'unknown' },
      { name: 'Old Oak', parish: 'Saint George', village_community: 'Roseau', category: 'Steel Band', era: '1950s–2000s', era_from: 1950, era_to: 2000, genre: 'Steel Band', status: 'unknown' },
      { name: 'Pan in Harmony', parish: 'Saint George', village_community: 'Roseau', category: 'Steel Band', era: '1950s–2000s', era_from: 1950, era_to: 2000, genre: 'Steel Band', status: 'unknown' },
      { name: 'Panalec', parish: 'Saint George', village_community: 'Roseau', category: 'Steel Band', era: '1950s–2000s', era_from: 1950, era_to: 2000, genre: 'Steel Band', status: 'unknown' },
      { name: 'Phaze 5', parish: 'Saint George', village_community: 'Roseau', category: 'Steel Band', era: '1950s–2000s', era_from: 1950, era_to: 2000, genre: 'Steel Band', status: 'unknown' },
      { name: 'Regent', parish: 'Saint George', village_community: 'Roseau', category: 'Steel Band', era: '1950s–2000s', era_from: 1950, era_to: 2000, genre: 'Steel Band', status: 'unknown' },
      { name: 'Shell', parish: 'Saint George', village_community: 'Roseau', category: 'Steel Band', era: '1950s–2000s', era_from: 1950, era_to: 2000, genre: 'Steel Band', status: 'unknown' },
      { name: 'Vauxhall Harmonicats', parish: 'Saint George', village_community: 'Roseau', category: 'Steel Band', era: '1950s–2000s', era_from: 1950, era_to: 2000, genre: 'Steel Band', status: 'unknown' },
      { name: 'Malisa', parish: 'Saint Andrew', village_community: 'Atkinson', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Francois Bannis & The Humming Birds', parish: 'Saint David', village_community: 'Castlebruce', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Green Apples', parish: 'Saint David', village_community: 'Castlebruce', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Young Meters Combo', parish: 'Saint David', village_community: 'Castlebruce', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Havana Boys Jazz Band', parish: 'Saint Peter', village_community: 'Colihaut', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Jazz', status: 'dissolved' },
      { name: 'Rising Star Jazz Band', parish: 'Saint Peter', village_community: 'Colihaut', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Jazz', status: 'dissolved' },
      { name: 'UKDA Connection', diaspora_location: 'France', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'unknown' },
      { name: 'Chubby & His Roots Brothers', parish: 'Saint Luke', village_community: 'Grandbay', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Decendants (linked to Groovers)', parish: 'Saint Luke', village_community: 'Grandbay', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Deltones', parish: 'Saint Luke', village_community: 'Grandbay', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Honey Combs \'Outcasts', parish: 'Saint Luke', village_community: 'Grandbay', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Midnight Groovers', parish: 'Saint Patrick', village_community: 'Grandbay', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Midnight Groovers. Int', parish: 'Saint Patrick', village_community: 'Grandbay', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Play Boys', parish: 'Saint Luke', village_community: 'Grandbay', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Belles Combo', parish: 'Saint Joseph', village_community: 'Mahaut', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Embers', parish: 'Saint Joseph', village_community: 'Mahaut', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Black Affairs', parish: 'Saint Andrew', village_community: 'Marigot', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Blacket Hatchet', parish: 'Saint Andrew', village_community: 'Marigot', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Bright Flames', parish: 'Saint Andrew', village_community: 'Marigot', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Changes', parish: 'Saint Andrew', village_community: 'Marigot', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Examples', parish: 'Saint Andrew', village_community: 'Marigot', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Harder they come', parish: 'Saint Andrew', village_community: 'Marigot', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'MainRoots', parish: 'Saint Andrew', village_community: 'Marigot', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Manonridge', parish: 'Saint Andrew', village_community: 'Marigot', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Mercury', parish: 'Saint Andrew', village_community: 'Marigot', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Pat Stevens Orchestra', parish: 'Saint Andrew', village_community: 'Marigot', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Refugees', parish: 'Saint Andrew', village_community: 'Marigot', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Survivors', parish: 'Saint Andrew', village_community: 'Marigot', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Caribbean Xtasy', parish: 'Saint Andrew', village_community: 'Marigot/BVI', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Henry and the Saints', parish: 'Saint Luke', village_community: 'Pointe Michel', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Rocking Lovers', parish: 'Saint Luke', village_community: 'Pointe Michel', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Swinging Busters', parish: 'Saint Luke', village_community: 'Pointe Michel', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Axis', parish: 'Saint John', village_community: 'Portsmouth', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Lawrence Brothers', parish: 'Saint John', village_community: 'Portsmouth', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Milestone', parish: 'Saint John', village_community: 'Portsmouth', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Modules', parish: 'Saint John', village_community: 'Portsmouth', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Pure Honey', parish: 'Saint John', village_community: 'Portsmouth', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Sticks and Stones', parish: 'Saint John', village_community: 'Portsmouth', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Stone Bloods', parish: 'Saint John', village_community: 'Portsmouth', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Technics', parish: 'Saint John', village_community: 'Portsmouth', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Voltage Four', parish: 'Saint John', village_community: 'Portsmouth', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: '1st Sonata', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'African Stalwarts', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'B - Blood (Black Blood)', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Bil O Men', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Black Machine', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Black Roots', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Blues Busters', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'B-Plus', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'C-Cat', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'De Boys and Dem', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Diamonds', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Earth', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Eclipse', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Emphasis', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Every Mothers Child', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Exile House', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Exile One', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Explosions', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Gaylords', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Gaylords Power Union', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Getto Roots', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Harmony Ten', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Ignitions', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Jewels (Swinging Stars Combo)', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Liquid Ice', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Los Caballeros', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Mantra', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Missin  Dimensions', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Naked Feet', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Naked Feet - Part 2', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Oxygen', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Pistons', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Rainbow Jazz', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Jazz', status: 'dissolved' },
      { name: 'Sandal Wood', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Security Pearls', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Shadows', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Silver Tones', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Smoke', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Softees Harmonics', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Swingin\' Stars', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Swinging Busters', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Swinging Teens', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Telstars', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'The Jerries', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Unity', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Vibrators', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Vultures', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Wafrikai', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Weedies', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Willie & the Willie Cats', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Wooden Stool', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Saultone Orchestra (Exile One)', parish: 'Saint George', village_community: 'Roseau/Guadeloupe', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Impressions', parish: 'Saint Joseph', village_community: 'Salisbury', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Mammouth', parish: 'Saint Joseph', village_community: 'Salisbury', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Smoke Pots', parish: 'Saint Joseph', village_community: 'Salisbury', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Grammacks', parish: 'Saint Joseph', village_community: 'St. Joseph', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Wax Power Vibrations', parish: 'Saint Joseph', village_community: 'St. Joseph', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Bionics', parish: 'Saint Andrew', village_community: 'Wesley', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Groovy Cats', parish: 'Saint Andrew', village_community: 'Wesley', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Steady Vibes', parish: 'Saint Andrew', village_community: 'Wesley/Canada', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Night Clouds', parish: 'Saint Andrew', village_community: 'Woodfordhill', category: 'Band', era: '1960s–1970s', era_from: 1960, era_to: 1970, genre: 'Calypso / Cadence-Lypso', status: 'dissolved' },
      { name: 'Sisserou', diaspora_location: 'England', category: 'Cultural / Chorale', era: '1960s–2000', era_from: 1960, era_to: 2000, genre: 'Folk Heritage / Chorale', status: 'unknown' },
      { name: 'La Jeune Etoile', parish: 'Saint Luke', village_community: 'Grandbay', category: 'Cultural / Chorale', era: '1960s–2000', era_from: 1960, era_to: 2000, genre: 'Folk Heritage / Chorale', status: 'unknown' },
      { name: 'Tradibelle Cultural Group', parish: 'Saint Luke', village_community: 'Grandbay', category: 'Cultural / Chorale', era: '1960s–2000', era_from: 1960, era_to: 2000, genre: 'Folk Heritage / Chorale', status: 'unknown' },
      { name: 'Fan Pan', parish: 'Saint George', village_community: 'Roseau', category: 'Cultural / Chorale', era: '1960s–2000', era_from: 1960, era_to: 2000, genre: 'Steel Band', status: 'unknown' },
      { name: 'Siffleur Montagne', parish: 'Saint George', village_community: 'Roseau', category: 'Cultural / Chorale', era: '1960s–2000', era_from: 1960, era_to: 2000, genre: 'Folk Heritage / Chorale', status: 'unknown' },
      { name: 'Sisserou Singers', parish: 'Saint George', village_community: 'Roseau', category: 'Cultural / Chorale', era: '1960s–2000', era_from: 1960, era_to: 2000, genre: 'Folk Heritage / Chorale', status: 'unknown' },
      { name: 'Colihaut  Jing Ping', parish: 'Saint Peter', village_community: 'Colihaut', category: 'Jing Ping / Folk', era: '1960s–2000s', era_from: 1960, era_to: 2000, genre: 'Jing Ping', status: 'unknown' },
      { name: 'Morill Lecointe', parish: 'Saint Peter', village_community: 'Colihaut', category: 'Jing Ping / Folk', era: '1960s–2000s', era_from: 1960, era_to: 2000, genre: 'Jing Ping / Folk', status: 'unknown' },
      { name: 'Giraudel Jing Ping', parish: 'Saint George', village_community: 'Giraudel', category: 'Jing Ping / Folk', era: '1960s–2000s', era_from: 1960, era_to: 2000, genre: 'Jing Ping', status: 'unknown' },
      { name: 'Peter Richards Group', diaspora_location: 'New York', category: 'Jing Ping / Folk', era: '1960s–2000s', era_from: 1960, era_to: 2000, genre: 'Jing Ping / Folk', status: 'unknown' },
      { name: 'Gutter', parish: 'Saint George', village_community: 'Roseau', category: 'Jing Ping / Folk', era: '1960s–2000s', era_from: 1960, era_to: 2000, genre: 'Jing Ping / Folk', status: 'unknown' },
      { name: 'Mahaut', parish: 'Saint George', village_community: 'Roseau', category: 'Jing Ping / Folk', era: '1960s–2000s', era_from: 1960, era_to: 2000, genre: 'Jing Ping / Folk', status: 'unknown' },
      { name: 'New Town Jing Ping', parish: 'Saint George', village_community: 'Roseau', category: 'Jing Ping / Folk', era: '1960s–2000s', era_from: 1960, era_to: 2000, genre: 'Jing Ping', status: 'unknown' },
      { name: 'Sugar Fire', parish: 'Saint George', village_community: 'Roseau', category: 'Jing Ping / Folk', era: '1960s–2000s', era_from: 1960, era_to: 2000, genre: 'Jing Ping / Folk', status: 'unknown' },
      { name: 'Warner Jing Ping', parish: 'Saint George', village_community: 'Warner', category: 'Jing Ping / Folk', era: '1960s–2000s', era_from: 1960, era_to: 2000, genre: 'Jing Ping', status: 'unknown' },
      { name: 'Freemix', diaspora_location: 'Broklyn, New York', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'unknown' },
      { name: 'Upper Levels', diaspora_location: 'Broklyn, New York', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'unknown' },
      { name: 'Soca Boyz Band', diaspora_location: 'Bronx, New York', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Soca', status: 'unknown' },
      { name: 'Levitasyon', diaspora_location: 'Canada', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'unknown' },
      { name: 'Zano', diaspora_location: 'Canada', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'unknown' },
      { name: '(Seven Seas)Roots Stem & Branches (RSB)', parish: 'Saint George', village_community: 'Canefield', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'DDL (Devoted Dynamic  ?….)', parish: 'Saint George', village_community: 'Canefield', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Neek', parish: 'Unknown', village_community: 'Dubique', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Impluse Band', diaspora_location: 'England', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'unknown' },
      { name: 'K-Passa', diaspora_location: 'England', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'unknown' },
      { name: 'Grammacks New Generation', diaspora_location: 'France', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'unknown' },
      { name: 'Demolition Crew', diaspora_location: 'New York', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'unknown' },
      { name: 'Fingees', diaspora_location: 'New York', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'unknown' },
      { name: 'Extasy', parish: 'Saint David', village_community: 'Petite Savanne', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'First Serenade', parish: 'Saint Luke', village_community: 'Pt Michel', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Christoes', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Cliché', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Eclipse', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Effex', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Eradication Squad', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Flintstones', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Fourth Generation', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Getto Vibes', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Ghetto Affairs', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'High Tension', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Impromptu', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'King Dreads', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Millette & the Professionals', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Partners in Kryme', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Queen of Hearts', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Rainbow Rockers', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Raw Redeem', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Remnant of Judah', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Roof Top Connection', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Second Chapter', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Seramix', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Stalwarts', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Stylee', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Sub Urban', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'WCK', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Rainbow Serpent', parish: 'Saint Andrew', village_community: 'Salybia/ Kalinago Territory', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'C-Top 6', parish: 'Saint Mark', village_community: 'Soufriere/scotts Head', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Volt Face', parish: 'Saint Joseph', village_community: 'St. Joseph', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'dissolved' },
      { name: 'Impulse Band', diaspora_location: 'Tampa. Florida', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'unknown' },
      { name: 'Masada', diaspora_location: 'Tortola', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'unknown' },
      { name: 'Moja Nya', diaspora_location: 'Washington DC', category: 'Band', era: '1980s–1990s', era_from: 1980, era_to: 1990, genre: 'Bouyon / Reggae / Soca', status: 'unknown' },
      { name: 'Eratic', diaspora_location: 'Canada', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Ratik', diaspora_location: 'Canada', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Reggae Cowboys', diaspora_location: 'Canada', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Reggae', status: 'unknown' },
      { name: 'Gizzae', diaspora_location: 'Chicago', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Hurricane Reggae Band', diaspora_location: 'Chicago', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Reggae', status: 'unknown' },
      { name: 'Sacaboyz', diaspora_location: 'Florida', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Song Masters', parish: 'Saint Andrew', village_community: 'Good Hope', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'IC Band', parish: 'Saint Andrew', village_community: 'Kalinago', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Triple Kay', parish: 'Saint George', village_community: 'Laudat', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Mahaut Row Row', parish: 'Saint Joseph', village_community: 'Mahaut', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Royalty Band', diaspora_location: 'New Jersey', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Reinjah Band', diaspora_location: 'New York', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Digital Stars', parish: 'Saint David', village_community: 'Petite Savanne', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Sout  Experience Band', parish: 'Saint David', village_community: 'Petite Savanne', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Thunder Roots', parish: 'Saint David', village_community: 'Petite Savanne', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Reaction One', parish: 'Saint Luke', village_community: 'Pointe Michel', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'MFR', parish: 'Saint John', village_community: 'Portsmouth', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Riddim Knockers', parish: 'Saint John', village_community: 'Portsmouth', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Danger Band', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Inner Corps', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Mystic Vibrations', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Original Bouyon Pioneers', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Outta Band', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Riddim & Heat', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Sickleberry', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Signal Band', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Smith Brothers', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Tropic Tension', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'WCK Next Generation', parish: 'Saint George', village_community: 'Roseau', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Damage Band', diaspora_location: 'St Croix, USVI', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Ti Orkest', parish: 'Saint Joseph', village_community: 'St Joseph', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Cool Session Brass', diaspora_location: 'St. John, USVI', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Look US Band', parish: 'Saint George', village_community: 'Trafalgar', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Breve', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'End Time Singers', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Folk Heritage / Chorale', status: 'unknown' },
      { name: 'Fanatik', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Ujama', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Visionaries', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' },
      { name: 'Wasin Warriors', category: 'Band', era: '2000s', era_from: 2000, era_to: 2009, genre: 'Bouyon / Digital Era', status: 'unknown' }
    ];

    const result = await base44.asServiceRole.entities.Band.bulkCreate(bandsData);
    return Response.json({ success: true, created: result.length });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});